// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA01nH-kZqxQzd-JlAZ4qO1CPdUC5iugUc',
    appId: '1:894177842831:web:225fc2a55ebb2c50de02fa',
    messagingSenderId: '894177842831',
    projectId: 'fir-test-a5229',
    authDomain: 'fir-test-a5229.firebaseapp.com',
    storageBucket: 'fir-test-a5229.appspot.com',
    measurementId: 'G-TWC9F10DWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9cl80OVJ78s5fLaiXP4Li3VncAUJ5Cs',
    appId: '1:894177842831:android:da1c78f0376c951ede02fa',
    messagingSenderId: '894177842831',
    projectId: 'fir-test-a5229',
    storageBucket: 'fir-test-a5229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpyYg8qHuE9u9kENiuuJLfbCCYSZ-AMw',
    appId: '1:894177842831:ios:85c30e14316beaadde02fa',
    messagingSenderId: '894177842831',
    projectId: 'fir-test-a5229',
    storageBucket: 'fir-test-a5229.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpyYg8qHuE9u9kENiuuJLfbCCYSZ-AMw',
    appId: '1:894177842831:ios:85c30e14316beaadde02fa',
    messagingSenderId: '894177842831',
    projectId: 'fir-test-a5229',
    storageBucket: 'fir-test-a5229.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
